-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.offers
(
    id_offer serial NOT NULL,
    name_vacant_postion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    salary character varying(10) COLLATE pg_catalog."default" NOT NULL,
    date_of_posted timestamp without time zone NOT NULL,
    id_type bigint NOT NULL,
    id_company bigint NOT NULL,
    CONSTRAINT offers_pkey PRIMARY KEY (id_offer)
);

CREATE TABLE IF NOT EXISTS public.type
(
    id_type serial NOT NULL,
    name_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_pkey PRIMARY KEY (id_type)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    id_company serial NOT NULL,
    name_company character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ubication character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id_user bigint NOT NULL,
    CONSTRAINT companies_pkey PRIMARY KEY (id_company)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mail character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.students
(
    id_student serial NOT NULL,
    name_student character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name_student character varying(60) COLLATE pg_catalog."default" NOT NULL,
    mail_student character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telephone_student character varying(20) COLLATE pg_catalog."default" NOT NULL,
    id_user bigint NOT NULL,
    id_career bigint NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (id_student)
);

CREATE TABLE IF NOT EXISTS public.careers
(
    id_career serial NOT NULL,
    name_career character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_school bigint NOT NULL,
    CONSTRAINT careers_pkey PRIMARY KEY (id_career)
);

CREATE TABLE IF NOT EXISTS public.schools
(
    id_school serial NOT NULL,
    name_school character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ubication character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT schools_pkey PRIMARY KEY (id_school)
);

CREATE TABLE IF NOT EXISTS public.experiences
(
    id_experience serial NOT NULL,
    skill character varying(255) COLLATE pg_catalog."default" NOT NULL,
    knowledge character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT experiences_pkey PRIMARY KEY (id_experience)
);

CREATE TABLE IF NOT EXISTS public.applications
(
    id_application serial NOT NULL,
    date_of_application timestamp without time zone NOT NULL,
    status character varying(3) COLLATE pg_catalog."default" NOT NULL,
    id_offer bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT applications_pkey PRIMARY KEY (id_application)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id_comment serial NOT NULL,
    content character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    id_offer bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id_comment)
);

CREATE TABLE IF NOT EXISTS public.events_participation
(
    id_event_participation serial NOT NULL,
    id_event bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT events_participation_pkey PRIMARY KEY (id_event_participation)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id_event serial NOT NULL,
    name_event character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_advising bigint NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id_event)
);

CREATE TABLE IF NOT EXISTS public.advising
(
    id_advising serial NOT NULL,
    name_advising character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT advising_pkey PRIMARY KEY (id_advising)
);

ALTER TABLE IF EXISTS public.offers
    ADD CONSTRAINT offers_fk5 FOREIGN KEY (id_type)
    REFERENCES public.type (id_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.offers
    ADD CONSTRAINT offers_fk6 FOREIGN KEY (id_company)
    REFERENCES public.companies (id_company) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.companies
    ADD CONSTRAINT companies_fk4 FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT students_fk5 FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT students_fk6 FOREIGN KEY (id_career)
    REFERENCES public.careers (id_career) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.careers
    ADD CONSTRAINT careers_fk2 FOREIGN KEY (id_school)
    REFERENCES public.schools (id_school) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.experiences
    ADD CONSTRAINT experiences_fk5 FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.applications
    ADD CONSTRAINT applications_fk3 FOREIGN KEY (id_offer)
    REFERENCES public.offers (id_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.applications
    ADD CONSTRAINT applications_fk4 FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_fk0 FOREIGN KEY (id_offer)
    REFERENCES public.offers (id_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_fk1 FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.events_participation
    ADD CONSTRAINT events_participation_fk0 FOREIGN KEY (id_event)
    REFERENCES public.events (id_event) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.events_participation
    ADD CONSTRAINT events_participation_fk1 FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_fk0 FOREIGN KEY (id_advising)
    REFERENCES public.advising (id_advising) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;