BEGIN;
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
-- =========================================================
-- 1. GESTIÓN DE USUARIOS Y ROLES (AUTENTICACIÓN)
-- =========================================================
-- Tabla de Usuarios: Almacena las credenciales de acceso (correo y contraseña).
-- Es la tabla central para el login.
CREATE TABLE IF NOT EXISTS public.users
(  id_user serial NOT NULL,
    mail character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_role integer NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT users_mail_key UNIQUE (mail)
);

-- Tabla de Roles: Define los tipos de usuarios permitidos en el sistema.
-- Ejemplos: 1=Administrador, 2=Estudiante, 3=Empresa.
CREATE TABLE IF NOT EXISTS public.roles
(
    id_role serial NOT NULL,
    name_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id_role),
    CONSTRAINT roles_name_unique UNIQUE (name_role)
);

-- Tabla de Administradores: Perfil específico para el personal de la institución
-- que gestionará la plataforma y validará ofertas.
CREATE TABLE IF NOT EXISTS public.administrators
(
    id_admin serial NOT NULL,
    name_admin character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name_admin character varying(60) COLLATE pg_catalog."default" NOT NULL,
    department character varying(50) COLLATE pg_catalog."default" DEFAULT 'General'::character varying,
    id_user bigint NOT NULL,
    CONSTRAINT administrators_pkey PRIMARY KEY (id_admin),
    CONSTRAINT administrators_id_user_key UNIQUE (id_user)
);

-- =========================================================
-- 2. PERFILES DE ESTUDIANTES Y DATOS ACADÉMICOS
-- =========================================================

-- Tabla de Estudiantes: Contiene la información personal del alumno.
-- Se vincula a la tabla 'users' para su acceso.
CREATE TABLE IF NOT EXISTS public.students
(
    id_student serial NOT NULL,
    name_student character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name_student character varying(60) COLLATE pg_catalog."default" NOT NULL,
    telephone_student character varying(20) COLLATE pg_catalog."default" NOT NULL,
    id_user bigint NOT NULL,
    id_career bigint NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (id_student),
    CONSTRAINT students_id_user_key UNIQUE (id_user));
-- Tabla de Carreras: Catálogo de programas educativos ofertados (ej. Ing. Sistemas).
CREATE TABLE IF NOT EXISTS public.careers
(
    id_career serial NOT NULL,
    name_career character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_school bigint NOT NULL,
    CONSTRAINT careers_pkey PRIMARY KEY (id_career)
);

-- Tabla de Escuelas: Catálogo de facultades o planteles de la institución.
CREATE TABLE IF NOT EXISTS public.schools
(
    id_school serial NOT NULL,
    name_school character varying(50) COLLATE pg_catalog."default" NOT NULL,
    location character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT schools_pkey PRIMARY KEY (id_school)
);
-- Tabla de Experiencias: Historial laboral o académico que el estudiante añade a su CV.
CREATE TABLE IF NOT EXISTS public.experiences
(
    id_experience serial NOT NULL,
    skill character varying(255) COLLATE pg_catalog."default" NOT NULL,
    knowledge character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT experiences_pkey PRIMARY KEY (id_experience)
);

-- =========================================================
-- 3. EMPRESAS, OFERTAS Y APLICACIONES
-- =========================================================

-- Tabla de Aplicaciones: Registro de postulaciones. Vincula a un estudiante con una oferta.
-- El estado por defecto es 'Pending'.
CREATE TABLE IF NOT EXISTS public.applications
(
    id_application serial NOT NULL,
    date_of_application timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    id_offer bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT applications_pkey PRIMARY KEY (id_application));	


-- Tabla de Ofertas: Las vacantes de trabajo publicadas por las empresas.
CREATE TABLE IF NOT EXISTS public.offers
(
    id_offer serial NOT NULL,
    name_vacant_position character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    salary numeric(10, 2) NOT NULL,
    date_of_posted timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_type bigint NOT NULL,
    id_company bigint NOT NULL,
    CONSTRAINT offers_pkey PRIMARY KEY (id_offer)
);

-- Tabla de Empresas: Perfil de las compañías reclutadoras.
CREATE TABLE IF NOT EXISTS public.companies
(
    id_company serial NOT NULL,
    name_company character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    location character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id_user bigint NOT NULL,
    logo_url character varying(255) COLLATE pg_catalog."default",
    website_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT companies_pkey PRIMARY KEY (id_company),
    CONSTRAINT companies_id_user_key UNIQUE (id_user)
);

-- Tabla de Tipos de Oferta: Categorías como 'Tiempo completo', 'Prácticas', etc.
CREATE TABLE IF NOT EXISTS public.type
(
    id_type serial NOT NULL,
    name_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_pkey PRIMARY KEY (id_type)
);

-- Tabla de Comentarios: Preguntas y respuestas públicas en las ofertas (tipo foro).
CREATE TABLE IF NOT EXISTS public.comments
(
    id_comment serial NOT NULL,
    content character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date date DEFAULT CURRENT_DATE,
    id_offer bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id_comment));
-- =========================================================
-- 4. SISTEMA DE MENSAJERÍA (INBOX Y ESTADOS)
-- =========================================================

-- Tabla de Estados del Chat: Catálogo para saber si un chat está 'Pendiente' o 'Contestado'.
CREATE TABLE IF NOT EXISTS public.statuses
(
    id_status serial NOT NULL,
    name_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT statuses_pkey PRIMARY KEY (id_status),
    CONSTRAINT statuses_name_unique UNIQUE (name_status));
-- ¡IMPORTANTE! Insertamos los estados básicos para que el sistema funcione.
INSERT INTO public.statuses (name_status, description) VALUES 
('Pendiente', 'El mensaje ha sido enviado pero la empresa aún no responde'),
('Contestado', 'La empresa ha enviado una respuesta al estudiante');

-- Tabla Inbox: Es el "HILO" principal de la conversación entre Estudiante y Empresa.
CREATE TABLE IF NOT EXISTS public.inbox
(
    id_inbox serial NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_status integer NOT NULL DEFAULT 1, -- Por defecto es 1 (Pendiente)
    id_student bigint NOT NULL,
    id_company bigint NOT NULL,
    CONSTRAINT inbox_pkey PRIMARY KEY (id_inbox)
);
-- Tabla de Mensajes del Inbox: Almacena lo que escribe el ESTUDIANTE.
CREATE TABLE IF NOT EXISTS public.inbox_messages
(
    id_inbox_message serial NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    sent_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_inbox bigint NOT NULL,
    CONSTRAINT inbox_messages_pkey PRIMARY KEY (id_inbox_message)
);
-- Tabla de Respuestas del Inbox: Almacena lo que responde la EMPRESA.
CREATE TABLE IF NOT EXISTS public.inbox_responses
(
    id_inbox_response serial NOT NULL,
    response_content text COLLATE pg_catalog."default" NOT NULL,
    response_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_inbox bigint NOT NULL,
    CONSTRAINT inbox_responses_pkey PRIMARY KEY (id_inbox_response)
);
-- =========================================================
-- 5. HABILIDADES (SKILLS)
-- =========================================================

-- Tabla de Skills: Catálogo maestro de habilidades (ej. Java, Python, SQL).
CREATE TABLE IF NOT EXISTS public.skills
(
    id_skill serial NOT NULL,
    name_skill character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT skills_pkey PRIMARY KEY (id_skill),
    CONSTRAINT skills_name_skill_key UNIQUE (name_skill)
);

-- Tabla Intermedia (Oferta - Skill): Qué habilidades requiere una oferta.
CREATE TABLE IF NOT EXISTS public.offer_skills
(
    id_offer bigint NOT NULL,
    id_skill integer NOT NULL,
    CONSTRAINT offer_skills_pkey PRIMARY KEY (id_offer, id_skill)
);

-- Tabla Intermedia (Estudiante - Skill): Qué habilidades posee un estudiante.
CREATE TABLE IF NOT EXISTS public.student_skills
(
    id_student bigint NOT NULL,
    id_skill integer NOT NULL,
    CONSTRAINT student_skills_pkey PRIMARY KEY (id_student, id_skill)
);
-- =========================================================
-- 6. EVENTOS Y ASESORÍAS
-- =========================================================

-- Tabla de Eventos: Conferencias, ferias de empleo, talleres.
CREATE TABLE IF NOT EXISTS public.events
(
    id_event serial NOT NULL,
    name_event character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_advising bigint NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id_event)
);





-- Tabla de Participación: Registra qué estudiantes asistieron a qué eventos.
CREATE TABLE IF NOT EXISTS public.events_participation
(
    id_event_participation serial NOT NULL,
    id_event bigint NOT NULL,
    id_student bigint NOT NULL,
    CONSTRAINT events_participation_pkey PRIMARY KEY (id_event_participation)
);

-- Tabla de Asesorías: Categorías o tipos de eventos/orientación.
CREATE TABLE IF NOT EXISTS public.advising
(
    id_advising serial NOT NULL,
    name_advising character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT advising_pkey PRIMARY KEY (id_advising)
);






-- =========================================================
-- 7. RELACIONES (FOREIGN KEYS)
-- Estas sentencias conectan todas las tablas para mantener la integridad de datos.
-- =========================================================
-- Relación: Usuario -> Rol
ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_fk_role FOREIGN KEY (id_role)
    REFERENCES public.roles (id_role) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- Relación: Estudiante -> Carrera
ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT students_fk_career FOREIGN KEY (id_career)
    REFERENCES public.careers (id_career) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Relación: Estudiante -> Usuario (Login)
ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT students_fk_user FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS students_id_user_key
    ON public.students(id_user);

-- Relación: Carrera -> Escuela
ALTER TABLE IF EXISTS public.careers
    ADD CONSTRAINT careers_fk_school FOREIGN KEY (id_school)
    REFERENCES public.schools (id_school) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relación: Aplicación -> Oferta
ALTER TABLE IF EXISTS public.applications
    ADD CONSTRAINT applications_fk_offer FOREIGN KEY (id_offer)
    REFERENCES public.offers (id_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relación: Aplicación -> Estudiante
ALTER TABLE IF EXISTS public.applications
    ADD CONSTRAINT applications_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relación: Oferta -> Empresa
ALTER TABLE IF EXISTS public.offers
    ADD CONSTRAINT offers_fk_company FOREIGN KEY (id_company)
    REFERENCES public.companies (id_company) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
-- Relación: Oferta -> Tipo de Oferta
ALTER TABLE IF EXISTS public.offers
    ADD CONSTRAINT offers_fk_type FOREIGN KEY (id_type)
    REFERENCES public.type (id_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Relación: Empresa -> Usuario (Login)
ALTER TABLE IF EXISTS public.companies
    ADD CONSTRAINT companies_fk_user FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


CREATE INDEX IF NOT EXISTS companies_id_user_key
    ON public.companies(id_user);

-- Relaciones del sistema Inbox (Mensajería)
ALTER TABLE IF EXISTS public.inbox
    ADD CONSTRAINT inbox_fk_company FOREIGN KEY (id_company)
    REFERENCES public.companies (id_company) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.inbox
    ADD CONSTRAINT inbox_fk_status FOREIGN KEY (id_status)
    REFERENCES public.statuses (id_status) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.inbox
    ADD CONSTRAINT inbox_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inbox_messages
    ADD CONSTRAINT im_fk_inbox FOREIGN KEY (id_inbox)
    REFERENCES public.inbox (id_inbox) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.inbox_responses
    ADD CONSTRAINT ir_fk_inbox FOREIGN KEY (id_inbox)
    REFERENCES public.inbox (id_inbox) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relaciones de Comentarios
ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_fk_offer FOREIGN KEY (id_offer)
    REFERENCES public.offers (id_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Relaciones de Skills (Tablas intermedias)
ALTER TABLE IF EXISTS public.offer_skills
    ADD CONSTRAINT os_fk_offer FOREIGN KEY (id_offer)
    REFERENCES public.offers (id_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.offer_skills
    ADD CONSTRAINT os_fk_skill FOREIGN KEY (id_skill)
    REFERENCES public.skills (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.student_skills
    ADD CONSTRAINT ss_fk_skill FOREIGN KEY (id_skill)
    REFERENCES public.skills (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.student_skills
    ADD CONSTRAINT ss_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relaciones de Eventos
ALTER TABLE IF EXISTS public.events_participation
    ADD CONSTRAINT part_fk_event FOREIGN KEY (id_event)
    REFERENCES public.events (id_event) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.events_participation
    ADD CONSTRAINT part_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_fk_advising FOREIGN KEY (id_advising)
    REFERENCES public.advising (id_advising) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Relación: Experiencia -> Estudiante
ALTER TABLE IF EXISTS public.experiences
    ADD CONSTRAINT experiences_fk_student FOREIGN KEY (id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Relación: Administrador -> Usuario (Login)
ALTER TABLE IF EXISTS public.administrators
    ADD CONSTRAINT admin_fk_user FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS administrators_id_user_key
    ON public.administrators(id_user);

END;
